export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const RESET_COUNTER = 'RESET_COUNTER';

export const FETCH_LIST_TODO = 'FETCH_LIST_TODO';
export const FETCH_LIST_TODO_COMPLETED = 'FETCH_LIST_TODO_COMPLETED';
export const FETCH_LIST_TODO_FAILED = 'FETCH_LIST_TODO_FAILED';
